analytics: {}
color:
  brandColors:
    - '#D0D8C0'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#F8F8E0'
  brandStrength: 0.964644
  lightness: 0.823324
  rhythmicContrast: 0.905807
  saturation: 0.767571
cta: {}
layout_spectrum: 0.302631
name: WCSYA
opengraph: {}
purpose: []
typography_spectrum: 0.521381
